---
to: tap-<%=name%>/package.json
---
{
  "name": "@node-elt/tap-<%=name%>",
  "bin": {
    "<%=name%>": "./bin/tap-<%=name%>.js"
  },
  "version": "1.0.0",
  "description": "Singer tap, generated by @node-elt/tap-generator",
  "main": "src/",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.21.1",
    "commander": "^7.2.0",
    "dayjs": "^1.10.4",
    "fs-extra": "^9.1.0",
    "lodash": "^4.17.21",
    "pino": "^6.11.2",
    "pino-pretty": "^4.7.1"
  },
  "devDependencies": {
    "babel-eslint": "^10.1.0",
    "eslint": "^7.8.1",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-config-wesbos": "^1.0.1",
    "eslint-plugin-html": "^6.1.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.6",
    "eslint-plugin-react-hooks": "^4.1.2",
    "prettier": "^2.1.1"
  }
}


